---
# This playbook configures all the machines

- hosts: raspberrypi
  tasks:
    - name: Update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=604800
    - name: Upgrade all apt packages
      apt: upgrade=dist force_apt_get=yes
    - name: Install node-exporter
      become: yes
      apt:
        name: prometheus-node-exporter

- hosts: raspberrypi
  roles:
    - paulfantom.rpi_exporter


